# Generated by Django 5.0.8 on 2026-03-12 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CampusInitiative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('category', models.CharField(choices=[('green', 'Green Campus'), ('energy', 'Energy & Climate'), ('waste', 'Waste Management'), ('water', 'Water Management'), ('transport', 'Sustainable Transportation'), ('building', 'Green Buildings'), ('biodiversity', 'Biodiversity')], max_length=20)),
                ('summary', models.TextField()),
                ('metric', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'ordering': ['category', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('organization', models.CharField(blank=True, max_length=160)),
                ('subject', models.CharField(choices=[('general', 'General inquiry'), ('partnership', 'Partnership request'), ('report', 'Report request'), ('student', 'Student engagement')], max_length=20)),
                ('message', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='EngagementInitiative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('category', models.CharField(choices=[('social', 'Social Impact Project'), ('volunteer', 'Volunteer Program'), ('government', 'Government Partnership'), ('industry', 'Industry Collaboration'), ('training', 'Community Training')], max_length=20)),
                ('summary', models.TextField()),
                ('audience', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'ordering': ['category', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(choices=[('event', 'Event'), ('conference', 'Conference'), ('workshop', 'Workshop')], max_length=20)),
                ('summary', models.TextField()),
                ('details', models.TextField()),
                ('start_date', models.DateField()),
                ('venue', models.CharField(max_length=160)),
                ('audience', models.CharField(max_length=160)),
            ],
            options={
                'ordering': ['start_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='GovernanceRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('responsibility', models.TextField()),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='InsightMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=160)),
                ('value', models.CharField(max_length=40)),
                ('context', models.CharField(max_length=200)),
                ('page_scope', models.CharField(choices=[('home', 'Home'), ('insights', 'Insights'), ('both', 'Both')], default='both', max_length=20)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(choices=[('policy', 'Policy Update'), ('research', 'Research'), ('campus', 'Campus'), ('engagement', 'Engagement')], max_length=20)),
                ('summary', models.TextField()),
                ('body', models.TextField()),
                ('published_on', models.DateField()),
                ('featured', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-published_on', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('partner_type', models.CharField(max_length=80)),
                ('website', models.URLField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ResearchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('category', models.CharField(choices=[('project', 'SDG Research Project'), ('publication', 'SDG Publication'), ('center', 'Research Center'), ('innovation', 'Innovation and Startup'), ('grant', 'Grant and Funding'), ('course', 'SDG-related Course'), ('program', 'Degree Program'), ('student', 'Student Project'), ('mooc', 'MOOC / Training')], max_length=20)),
                ('summary', models.TextField()),
                ('department', models.CharField(blank=True, max_length=120)),
                ('highlight_metric', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'ordering': ['category', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SDG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(unique=True)),
                ('title', models.CharField(max_length=120)),
                ('short_description', models.CharField(max_length=255)),
                ('overview', models.TextField()),
                ('university_actions', models.TextField()),
                ('indicators', models.TextField()),
                ('color_class', models.CharField(max_length=20)),
                ('featured', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=200)),
                ('short_name', models.CharField(default='SDG', max_length=40)),
                ('tagline', models.CharField(max_length=255)),
                ('hero_title', models.CharField(max_length=255)),
                ('hero_text', models.TextField()),
                ('rector_name', models.CharField(max_length=120)),
                ('rector_title', models.CharField(max_length=120)),
                ('rector_message', models.TextField()),
                ('sustainability_strategy', models.TextField()),
                ('governance_overview', models.TextField()),
                ('contact_address', models.CharField(max_length=255)),
                ('contact_phone', models.CharField(max_length=50)),
                ('contact_email', models.EmailField(max_length=254)),
                ('office_hours', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name_plural': 'Site settings',
            },
        ),
        migrations.CreateModel(
            name='SustainabilityPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('category', models.CharField(choices=[('environment', 'Environment'), ('education', 'Education'), ('procurement', 'Procurement'), ('research', 'Research'), ('risk', 'Risk'), ('disclosure', 'Disclosure')], max_length=20)),
                ('summary', models.TextField()),
                ('published_on', models.DateField()),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='SustainabilityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('report_type', models.CharField(choices=[('annual', 'Annual Report'), ('ranking', 'Ranking Submission'), ('dashboard', 'Dashboard'), ('policy', 'Policy Digest')], max_length=20)),
                ('summary', models.TextField()),
                ('publish_date', models.DateField()),
                ('download_url', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['-publish_date'],
            },
        ),
        migrations.CreateModel(
            name='SDGProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('summary', models.TextField()),
                ('project_type', models.CharField(max_length=80)),
                ('sdg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='portal.sdg')),
            ],
            options={
                'ordering': ['sdg__number', 'title'],
            },
        ),
    ]
