# Generated by Django 5.0.8 on 2026-03-12 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0002_seed_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="hero_background_image",
            field=models.FileField(blank=True, upload_to="hero/"),
        ),
    ]
