# Generated by Django 5.1.6 on 2026-03-13 15:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_sitesettings_hero_background_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('subtitle', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField()),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department_name', models.CharField(max_length=160)),
                ('contact_person', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('office_location', models.CharField(max_length=160)),
                ('office_hours', models.CharField(max_length=120)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'department_name'],
            },
        ),
        migrations.CreateModel(
            name='EducationInitiative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('curriculum', 'Curriculum'), ('training', 'Training'), ('fellowship', 'Fellowship'), ('outreach', 'Public Initiative')], max_length=20)),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(unique=True)),
                ('summary', models.TextField()),
                ('body', models.TextField()),
                ('audience', models.CharField(max_length=140)),
                ('delivery_model', models.CharField(blank=True, max_length=140)),
                ('featured', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='HeroStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.CharField(max_length=40)),
                ('label', models.CharField(max_length=140)),
                ('description', models.CharField(max_length=220)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ImpactMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=160)),
                ('value', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=220)),
                ('scope', models.CharField(choices=[('home', 'Home'), ('reports', 'Reports'), ('both', 'Both')], default='both', max_length=20)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='InstitutionalValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page_key', models.CharField(choices=[('home', 'Home'), ('about', 'About'), ('programs', 'Goals / Programs / Services'), ('research', 'Research / Projects'), ('education', 'Education / Initiatives'), ('sustainability', 'Sustainability / Strategy / Policy'), ('reports', 'Reports & Insights'), ('news', 'News & Events'), ('contact', 'Contact')], max_length=30, unique=True)),
                ('eyebrow', models.CharField(max_length=120)),
                ('title', models.CharField(max_length=220)),
                ('intro', models.TextField()),
                ('supporting_title', models.CharField(blank=True, max_length=180)),
                ('supporting_text', models.TextField(blank=True)),
                ('cta_title', models.CharField(blank=True, max_length=180)),
                ('cta_text', models.TextField(blank=True)),
                ('cta_primary_label', models.CharField(blank=True, max_length=80)),
                ('cta_primary_url', models.CharField(blank=True, max_length=255)),
                ('cta_secondary_label', models.CharField(blank=True, max_length=80)),
                ('cta_secondary_url', models.CharField(blank=True, max_length=255)),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.CharField(blank=True, max_length=320)),
            ],
            options={
                'verbose_name': 'Page content',
                'verbose_name_plural': 'Page contents',
                'ordering': ['page_key'],
            },
        ),
        migrations.CreateModel(
            name='PolicyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('strategy', 'Strategy'), ('policy', 'Policy'), ('framework', 'Framework'), ('regulation', 'Regulation')], max_length=20)),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(unique=True)),
                ('summary', models.TextField()),
                ('body', models.TextField()),
                ('publish_date', models.DateField()),
                ('effective_period', models.CharField(blank=True, max_length=120)),
                ('featured', models.BooleanField(default=False)),
                ('file', models.FileField(blank=True, upload_to='policies/')),
                ('external_url', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['-publish_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('goal', 'Strategic Goal'), ('program', 'Flagship Program'), ('service', 'Institutional Service')], max_length=20)),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(unique=True)),
                ('summary', models.TextField()),
                ('body', models.TextField()),
                ('outcome_value', models.CharField(blank=True, max_length=80)),
                ('outcome_label', models.CharField(blank=True, max_length=120)),
                ('featured', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_type', models.CharField(choices=[('annual', 'Annual report'), ('insight', 'Insight brief'), ('ranking', 'Ranking submission'), ('dashboard', 'Data dashboard')], max_length=20)),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(unique=True)),
                ('summary', models.TextField()),
                ('body', models.TextField()),
                ('publish_date', models.DateField()),
                ('highlight_metric', models.CharField(blank=True, max_length=120)),
                ('file', models.FileField(blank=True, upload_to='reports/')),
                ('external_url', models.URLField(blank=True)),
                ('featured', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-publish_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ResearchProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('research', 'Research Program'), ('project', 'Strategic Project'), ('lab', 'Laboratory / Center'), ('collaboration', 'Partnership Project')], max_length=20)),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(unique=True)),
                ('summary', models.TextField()),
                ('body', models.TextField()),
                ('lead_unit', models.CharField(max_length=140)),
                ('timeframe', models.CharField(blank=True, max_length=120)),
                ('featured', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='StrategicPriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('icon', models.CharField(default='compass', max_length=40)),
                ('title', models.CharField(max_length=160)),
                ('summary', models.TextField()),
                ('metric', models.CharField(blank=True, max_length=120)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'title'],
            },
        ),
        migrations.DeleteModel(
            name='CampusInitiative',
        ),
        migrations.DeleteModel(
            name='EngagementInitiative',
        ),
        migrations.DeleteModel(
            name='InsightMetric',
        ),
        migrations.DeleteModel(
            name='ResearchItem',
        ),
        migrations.RemoveField(
            model_name='sdgproject',
            name='sdg',
        ),
        migrations.DeleteModel(
            name='SustainabilityPolicy',
        ),
        migrations.DeleteModel(
            name='SustainabilityReport',
        ),
        migrations.AlterModelOptions(
            name='contactsubmission',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Site settings', 'verbose_name_plural': 'Site settings'},
        ),
        migrations.RemoveField(
            model_name='contactsubmission',
            name='submitted_at',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='contact_address',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='contact_phone',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='hero_background_image',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='hero_text',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='rector_message',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='rector_name',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='rector_title',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='short_name',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='site_name',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='sustainability_strategy',
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='event',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='governancerole',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='governancerole',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='partner',
            name='description',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name='partner',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='address',
            field=models.CharField(default='12 Mustaqillik Avenue, Tashkent, Uzbekistan', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email',
            field=models.EmailField(default='office@institution.uz', max_length=254),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_text',
            field=models.TextField(default='Built for official communication, public accountability, and coordinated institutional execution.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_description',
            field=models.TextField(default='This platform presents official strategy, flagship programs, research portfolios, educational initiatives, public reports, and stakeholder engagement in a unified and trusted digital environment.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_kicker',
            field=models.CharField(default='National-scale institutional platform', max_length=120),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_primary_label',
            field=models.CharField(default='Explore Strategic Priorities', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_primary_url',
            field=models.CharField(default='/programs/', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_secondary_label',
            field=models.CharField(default='View Reports & Insights', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_secondary_url',
            field=models.CharField(default='/reports-insights/', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='institution_name',
            field=models.CharField(default='Sustainable Development Governance Platform', max_length=220),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='institution_short_name',
            field=models.CharField(default='SDG', max_length=40),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='leader_message',
            field=models.TextField(default='We are building a platform that reflects institutional maturity: one that is rigorous in governance, clear in communication, confident in design, and accountable in results. Every section of this portal is structured to strengthen trust among students, researchers, partners, public bodies, and international stakeholders.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='leader_name',
            field=models.CharField(default='Professor Kamoliddin Ergashev', max_length=120),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='leader_signature',
            field=models.CharField(default='Leadership Office', max_length=120),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='leader_title',
            field=models.CharField(default='Rector and Chair of the Strategic Council', max_length=120),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='map_embed_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_description',
            field=models.CharField(default='Official premium institutional web platform for sustainability strategy, programs, research, education, reports, and stakeholder engagement.', max_length=320),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_title',
            field=models.CharField(default='Sustainable Development Governance Platform', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='mission',
            field=models.TextField(default='To lead a transparent, research-driven, and future-oriented sustainability transformation across education, governance, operations, and public partnerships.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='navbar_cta_label',
            field=models.CharField(default='Reports Center', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='navbar_cta_url',
            field=models.CharField(default='/reports-insights/', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='official_badge',
            field=models.CharField(default='Official Institutional Portal', max_length=120),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='overview_text',
            field=models.TextField(default='The platform aligns academic excellence, policy implementation, research leadership, and public service through a structured sustainability agenda designed for large-scale institutions.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='overview_title',
            field=models.CharField(default='Institutional overview', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='phone',
            field=models.CharField(default='+998 71 000 50 50', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='strategic_approach',
            field=models.TextField(default='Our strategic approach combines executive governance, measurable performance indicators, flagship programs, applied research, and stakeholder-facing reporting under one integrated digital architecture.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='strategy_overview',
            field=models.TextField(default='The strategy focuses on resilient infrastructure, climate-aware planning, inclusive education, data-led management, and cross-sector collaboration.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='vision',
            field=models.TextField(default='To become a benchmark institutional platform where trust, evidence, innovation, and strategic coordination advance long-term sustainable development outcomes.'),
        ),
        migrations.AlterField(
            model_name='contactsubmission',
            name='subject',
            field=models.CharField(choices=[('general', 'General inquiry'), ('partnership', 'Partnership request'), ('media', 'Media and communications'), ('report', 'Report and data request')], max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('forum', 'Forum'), ('conference', 'Conference'), ('workshop', 'Workshop'), ('briefing', 'Briefing')], max_length=20),
        ),
        migrations.AlterField(
            model_name='governancerole',
            name='title',
            field=models.CharField(max_length=140),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='category',
            field=models.CharField(choices=[('official', 'Official update'), ('research', 'Research'), ('program', 'Program'), ('event', 'Event')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='governance_overview',
            field=models.TextField(default='Governance is coordinated through senior leadership, policy committees, implementation teams, and data stewards responsible for delivery quality and institutional accountability.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_title',
            field=models.CharField(default='A premium institutional portal for sustainability leadership, education, and evidence-based public accountability.', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='office_hours',
            field=models.CharField(default='Monday-Friday, 09:00-18:00', max_length=120),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='tagline',
            field=models.CharField(default='Official institutional platform for sustainability governance, policy, and public reporting', max_length=255),
        ),
        migrations.DeleteModel(
            name='SDG',
        ),
        migrations.DeleteModel(
            name='SDGProject',
        ),
    ]
