# Generated by Django 5.0.14 on 2026-03-20 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_update_leader_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='image',
            field=models.ImageField(blank=True, upload_to='news/'),
        ),
    ]
