# Generated by Django 5.0.14 on 2026-03-20 20:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_newsarticle_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SDGWorkItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('goal_number', models.PositiveSmallIntegerField(choices=[(1, 'SDG 1'), (2, 'SDG 2'), (3, 'SDG 3'), (4, 'SDG 4'), (5, 'SDG 5'), (6, 'SDG 6'), (7, 'SDG 7'), (8, 'SDG 8'), (9, 'SDG 9'), (10, 'SDG 10'), (11, 'SDG 11'), (12, 'SDG 12'), (13, 'SDG 13'), (14, 'SDG 14'), (15, 'SDG 15'), (16, 'SDG 16'), (17, 'SDG 17')])),
                ('title', models.CharField(max_length=180)),
                ('summary', models.TextField()),
                ('details', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, upload_to='sdg_work_items/')),
                ('attachment', models.FileField(blank=True, upload_to='sdg_work_items/attachments/')),
                ('external_url', models.URLField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('featured', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'SDG work item',
                'verbose_name_plural': 'SDG work items',
                'ordering': ['goal_number', 'display_order', 'title'],
            },
        ),
    ]
