# Generated by Codex on 2026-03-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0010_alter_achievement_subtitle_alter_achievement_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsarticle",
            name="sdg_goal",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[(number, f"SDG {number}") for number in range(1, 18)],
                null=True,
            ),
        ),
    ]
